// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.25.3
// source: axtransport.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PCompression int32

const (
	PCompression_P_COMPRESSION_NONE PCompression = 0
	PCompression_P_COMPRESSION_GZIP PCompression = 1
)

// Enum value maps for PCompression.
var (
	PCompression_name = map[int32]string{
		0: "P_COMPRESSION_NONE",
		1: "P_COMPRESSION_GZIP",
	}
	PCompression_value = map[string]int32{
		"P_COMPRESSION_NONE": 0,
		"P_COMPRESSION_GZIP": 1,
	}
)

func (x PCompression) Enum() *PCompression {
	p := new(PCompression)
	*p = x
	return p
}

func (x PCompression) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PCompression) Descriptor() protoreflect.EnumDescriptor {
	return file_axtransport_proto_enumTypes[0].Descriptor()
}

func (PCompression) Type() protoreflect.EnumType {
	return &file_axtransport_proto_enumTypes[0]
}

func (x PCompression) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PCompression.Descriptor instead.
func (PCompression) EnumDescriptor() ([]byte, []int) {
	return file_axtransport_proto_rawDescGZIP(), []int{0}
}

type PEncryption int32

const (
	PEncryption_P_ENCRYPTION_NONE PEncryption = 0
	PEncryption_P_ENCRYPTION_AES  PEncryption = 1
)

// Enum value maps for PEncryption.
var (
	PEncryption_name = map[int32]string{
		0: "P_ENCRYPTION_NONE",
		1: "P_ENCRYPTION_AES",
	}
	PEncryption_value = map[string]int32{
		"P_ENCRYPTION_NONE": 0,
		"P_ENCRYPTION_AES":  1,
	}
)

func (x PEncryption) Enum() *PEncryption {
	p := new(PEncryption)
	*p = x
	return p
}

func (x PEncryption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PEncryption) Descriptor() protoreflect.EnumDescriptor {
	return file_axtransport_proto_enumTypes[1].Descriptor()
}

func (PEncryption) Type() protoreflect.EnumType {
	return &file_axtransport_proto_enumTypes[1]
}

func (x PEncryption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PEncryption.Descriptor instead.
func (PEncryption) EnumDescriptor() ([]byte, []int) {
	return file_axtransport_proto_rawDescGZIP(), []int{1}
}

type PPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload     []byte       `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Compression PCompression `protobuf:"varint,2,opt,name=compression,proto3,enum=com.axgrid.axtransport.PCompression" json:"compression,omitempty"`
	Encryption  PEncryption  `protobuf:"varint,3,opt,name=encryption,proto3,enum=com.axgrid.axtransport.PEncryption" json:"encryption,omitempty"`
}

func (x *PPacket) Reset() {
	*x = PPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_axtransport_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PPacket) ProtoMessage() {}

func (x *PPacket) ProtoReflect() protoreflect.Message {
	mi := &file_axtransport_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PPacket.ProtoReflect.Descriptor instead.
func (*PPacket) Descriptor() ([]byte, []int) {
	return file_axtransport_proto_rawDescGZIP(), []int{0}
}

func (x *PPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PPacket) GetCompression() PCompression {
	if x != nil {
		return x.Compression
	}
	return PCompression_P_COMPRESSION_NONE
}

func (x *PPacket) GetEncryption() PEncryption {
	if x != nil {
		return x.Encryption
	}
	return PEncryption_P_ENCRYPTION_NONE
}

var File_axtransport_proto protoreflect.FileDescriptor

var file_axtransport_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x78, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x78, 0x67, 0x72, 0x69, 0x64, 0x2e,
	0x61, 0x78, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x22, 0xb0, 0x01, 0x0a, 0x07,
	0x50, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x46, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x78, 0x67,
	0x72, 0x69, 0x64, 0x2e, 0x61, 0x78, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e,
	0x50, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x63, 0x6f,
	0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x0a, 0x65, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e,
	0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x78, 0x67, 0x72, 0x69, 0x64, 0x2e, 0x61, 0x78, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x50, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0a, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x3e,
	0x0a, 0x0c, 0x50, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x12, 0x50, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x52, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f,
	0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x5f, 0x43, 0x4f, 0x4d, 0x50,
	0x52, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x47, 0x5a, 0x49, 0x50, 0x10, 0x01, 0x2a, 0x3a,
	0x0a, 0x0b, 0x50, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a,
	0x11, 0x50, 0x5f, 0x45, 0x4e, 0x43, 0x52, 0x59, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x4f,
	0x4e, 0x45, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x5f, 0x45, 0x4e, 0x43, 0x52, 0x59, 0x50,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x45, 0x53, 0x10, 0x01, 0x42, 0x3e, 0x0a, 0x16, 0x63, 0x6f,
	0x6d, 0x2e, 0x61, 0x78, 0x67, 0x72, 0x69, 0x64, 0x2e, 0x61, 0x78, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x70, 0x6f, 0x72, 0x74, 0x50, 0x01, 0xaa, 0x02, 0x21, 0x41, 0x78, 0x47, 0x72, 0x69, 0x64, 0x2e,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x78, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_axtransport_proto_rawDescOnce sync.Once
	file_axtransport_proto_rawDescData = file_axtransport_proto_rawDesc
)

func file_axtransport_proto_rawDescGZIP() []byte {
	file_axtransport_proto_rawDescOnce.Do(func() {
		file_axtransport_proto_rawDescData = protoimpl.X.CompressGZIP(file_axtransport_proto_rawDescData)
	})
	return file_axtransport_proto_rawDescData
}

var file_axtransport_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_axtransport_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_axtransport_proto_goTypes = []interface{}{
	(PCompression)(0), // 0: com.axgrid.axtransport.PCompression
	(PEncryption)(0),  // 1: com.axgrid.axtransport.PEncryption
	(*PPacket)(nil),   // 2: com.axgrid.axtransport.PPacket
}
var file_axtransport_proto_depIdxs = []int32{
	0, // 0: com.axgrid.axtransport.PPacket.compression:type_name -> com.axgrid.axtransport.PCompression
	1, // 1: com.axgrid.axtransport.PPacket.encryption:type_name -> com.axgrid.axtransport.PEncryption
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_axtransport_proto_init() }
func file_axtransport_proto_init() {
	if File_axtransport_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_axtransport_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_axtransport_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_axtransport_proto_goTypes,
		DependencyIndexes: file_axtransport_proto_depIdxs,
		EnumInfos:         file_axtransport_proto_enumTypes,
		MessageInfos:      file_axtransport_proto_msgTypes,
	}.Build()
	File_axtransport_proto = out.File
	file_axtransport_proto_rawDesc = nil
	file_axtransport_proto_goTypes = nil
	file_axtransport_proto_depIdxs = nil
}
